// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LegacyMediaFilesOnDvd.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace LegacyMediaFilesOnDvd.Data.Context;

public partial class LegacyMediaFilesContext : DbContext
{
    public LegacyMediaFilesContext()
    {
    }

    public LegacyMediaFilesContext(DbContextOptions<LegacyMediaFilesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LegacyDisc> LegacyDiscs { get; set; }

    public virtual DbSet<LegacyFilename> LegacyFilenames { get; set; }

    public virtual DbSet<LegacyGenre> LegacyGenres { get; set; }

    public virtual DbSet<LegacyPerformer> LegacyPerformers { get; set; }

    public virtual DbSet<LegacyPerformerType> LegacyPerformerTypes { get; set; }

    public virtual DbSet<LegacyPublisher> LegacyPublishers { get; set; }

    public virtual DbSet<LegacySeries> LegacySeries { get; set; }

    public virtual DbSet<LegacyWallet> LegacyWallets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlite("Data Source=C:\\temp\\FilesOnDvd\\MigrationToSqlLite\\LegacyMediaFilesOnDvd.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LegacyDisc>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<LegacyFilename>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Disc).WithMany(p => p.LegacyFilenames).OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(d => d.Genre).WithMany(p => p.LegacyFilenames).OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Series).WithMany(p => p.LegacyFilenames).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<LegacyGenre>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<LegacyPerformer>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.PerformerType).WithMany(p => p.LegacyPerformers).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<LegacyPerformerType>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<LegacyPublisher>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<LegacySeries>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Genre).WithMany(p => p.LegacySeries).OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Publisher).WithMany(p => p.LegacySeries).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<LegacyWallet>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}