// <auto-generated />
using MediaFilesOnDvd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaFilesOnDvd.Data.Migrations
{
    [DbContext(typeof(MediaFilesContext))]
    [Migration("20260620205102_AddPerformerAliases")]
    partial class AddPerformerAliases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FileTagMediaFile", b =>
                {
                    b.Property<int>("MediaFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFilesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("FileTagMediaFile");
                });

            modelBuilder.Entity("MediaFilePerformer", b =>
                {
                    b.Property<int>("MediaFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFilesId", "PerformersId");

                    b.HasIndex("PerformersId");

                    b.ToTable("MediaFilePerformer");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Discs");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.FileGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileGenres");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.FileTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.GalleryPhotoUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.ToTable("GalleryPhotoUrls");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.HeadshotUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.ToTable("HeadshotUrl");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileGenreId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnwatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnknownPerformerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("FileGenreId");

                    b.HasIndex("SeriesId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerformerTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerformerTypeId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.PerformerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerformerTypes");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.ScreenshotUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.ToTable("ScreenshotUrls");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileGenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesPublisherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileGenreId");

                    b.HasIndex("SeriesPublisherId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.SeriesPublisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeriesPublishers");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageUnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FileTagMediaFile", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaFilesOnDvd.Data.Entities.FileTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaFilePerformer", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaFilesOnDvd.Data.Entities.Performer", null)
                        .WithMany()
                        .HasForeignKey("PerformersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Disc", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.Wallet", "Wallet")
                        .WithMany("Discs")
                        .HasForeignKey("WalletId");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.GalleryPhotoUrl", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.Performer", "Performer")
                        .WithMany("GalleryPhotoUrls")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.HeadshotUrl", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.Performer", null)
                        .WithMany("HeadshotUrls")
                        .HasForeignKey("PerformerId");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.MediaFile", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.Disc", "Disc")
                        .WithMany("Files")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaFilesOnDvd.Data.Entities.FileGenre", "FileGenre")
                        .WithMany("MediaFiles")
                        .HasForeignKey("FileGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaFilesOnDvd.Data.Entities.Series", "Series")
                        .WithMany("MediaFiles")
                        .HasForeignKey("SeriesId");

                    b.Navigation("Disc");

                    b.Navigation("FileGenre");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Performer", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.PerformerType", "Type")
                        .WithMany()
                        .HasForeignKey("PerformerTypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.ScreenshotUrl", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.MediaFile", "MediaFile")
                        .WithMany("Screenshots")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Series", b =>
                {
                    b.HasOne("MediaFilesOnDvd.Data.Entities.FileGenre", "FileGenre")
                        .WithMany("Series")
                        .HasForeignKey("FileGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaFilesOnDvd.Data.Entities.SeriesPublisher", "Publisher")
                        .WithMany("Series")
                        .HasForeignKey("SeriesPublisherId");

                    b.Navigation("FileGenre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Disc", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.FileGenre", b =>
                {
                    b.Navigation("MediaFiles");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.MediaFile", b =>
                {
                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Performer", b =>
                {
                    b.Navigation("GalleryPhotoUrls");

                    b.Navigation("HeadshotUrls");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Series", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.SeriesPublisher", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("MediaFilesOnDvd.Data.Entities.Wallet", b =>
                {
                    b.Navigation("Discs");
                });
#pragma warning restore 612, 618
        }
    }
}
