// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LegacyMediaFilesOnDvd.Data.Models;

public partial class LegacyDisc
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    public string Name { get; set; }

    public long? Wallet { get; set; }

    public string Notes { get; set; }

    [ForeignKey("Wallet")]
    [InverseProperty("LegacyDiscs")]
    public virtual LegacyWallet WalletNavigation { get; set; }
}