// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LegacyMediaFilesOnDvd.Data.Models;

public partial class LegacySeries
{
    [Key]
    public long Id { get; set; }

    public string Name { get; set; }

    public long? GenreId { get; set; }

    public long? PublisherId { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("LegacySeries")]
    public virtual LegacyGenre Genre { get; set; }

    [InverseProperty("Series")]
    public virtual ICollection<LegacyFilename> LegacyFilenames { get; } = new List<LegacyFilename>();

    [ForeignKey("PublisherId")]
    [InverseProperty("LegacySeries")]
    public virtual LegacyPublisher Publisher { get; set; }
}