// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LegacyMediaFilesOnDvd.Data.Models;

public partial class LegacyFilename
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    public string Name { get; set; }

    public long? GenreId { get; set; }

    public long? Disc { get; set; }

    public long? Series { get; set; }

    public string Notes { get; set; }

    public long? UnknownActors { get; set; }

    public string Unwatched { get; set; }

    [ForeignKey("Disc")]
    [InverseProperty("LegacyFilenames")]
    public virtual LegacyDisc DiscNavigation { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("LegacyFilenames")]
    public virtual LegacyGenre Genre { get; set; }
}